CREATE DATABASE SYSCONTEST;

USE SYSCONTEST;

CREATE TABLE INSTITUTION (
	idInstitution 		INT 		NOT NULL AUTO_INCREMENT,
	name				NVARCHAR(55),
	CONSTRAINT institutionPKC PRIMARY KEY (idInstitution)
);

CREATE TABLE DISCIPLINE (
	idDiscipline 		INT 		NOT NULL AUTO_INCREMENT,
	name 				NVARCHAR(45),
	CONSTRAINT 	disciplinePCK PRIMARY KEY (idDiscipline)
);

CREATE TABLE SUBJECT (
	idSubject 			INT 		NOT NULL AUTO_INCREMENT,
	name				NVARCHAR(45),
	idDiscipline		INT,
	CONSTRAINT subjectPKC PRIMARY KEY (idSubject),
	CONSTRAINT subjectFKT FOREIGN KEY (idDiscipline) REFERENCES DISCIPLINE(idDiscipline)
);

CREATE TABLE EXAM (
	idExam				INT 		NOT NULL AUTO_INCREMENT,
	idInstitution		INT, 
	year				INT,
	role				NVARCHAR(45),
	level				NVARCHAR(20),
	organ				NVARCHAR(55),
	CONSTRAINT examPKC PRIMARY KEY (idExam),
	CONSTRAINT examFKT FOREIGN KEY (idInstitution) REFERENCES INSTITUTION(idInstitution)
);


