
ALTER TABLE SUBJECT DROP FOREIGN KEY subjectFKT;
ALTER TABLE EXAM DROP FOREIGN KEY examFKT;
ALTER TABLE QUESTION DROP FOREIGN KEY questionFKT;

DROP TABLE INSTITUTION;
DROP TABLE DISCIPLINE;
DROP TABLE SUBJECT;
DROP TABLE EXAM;
DROP TABLE QUESTION;

DROP DATABASE SYSCONTEST;