

ALTER TABLE SUBJECT DROP FOREIGN KEY subjectFKT;
ALTER TABLE EXAM DROP FOREIGN KEY examFKT;
ALTER TABLE QUESTION DROP FOREIGN KEY questionFKT;
ALTER TABLE DISCIPLINE_QUESTION DROP FOREIGN KEY disciplineQuestionFKT;
ALTER TABLE DISCIPLINE_QUESTION DROP FOREIGN KEY disciplineQuestionFKt2;

DROP TABLE INSTITUTION;
DROP TABLE DISCIPLINE;
DROP TABLE SUBJECT;
DROP TABLE EXAM;
DROP TABLE QUESTION;
DROP TABLE DISCIPLINE_QUESTION;

DROP DATABASE SYSCONTEST;