
SELECT * FROM INSTITUTION;
SELECT * FROM DISCIPLINE;
SELECT * FROM SUBJECT;
SELECT * FROM EXAM;
SELECT * FROM QUESTION;

-- CONSULTAR TODOS OS SUBJECT DE CADA DISCIPLINA  --
SELECT S.idDiscipline, D.name, S.name, S.idSubject
FROM SUBJECT AS S, DISCIPLINE AS D
WHERE S.idDiscipline = D.idDiscipline;

-- CONSULTA RETORNA PARA O SYSCONTEST NO GRID QUESTOES --
SELECT * 
FROM QUESTION AS Q, ALTERNATIVE AS A
WHERE A.idQuestion = Q.idQuestion;
