
-- INSERT INTITUIÇÕES --
INSERT INTO INSTITUTION (name) VALUES('FUNDAÇÃO GERTÚLIO VARGAS');
INSERT INTO INSTITUTION (name) VALUES('UNIVERSIDADE ESTADUAL DA PARAIBA UEPB');
INSERT INTO INSTITUTION (name) VALUES('COMPROV');
INSERT INTO INSTITUTION (name) VALUES('FUNDAÇÃO CARLOS CHARGAS SOBRINHO');
INSERT INTO INSTITUTION (name) VALUES('UNIVERSIDADE FEDERAL DA PARAIBA');
INSERT INTO INSTITUTION (name) VALUES('PUC RIO');
-- INSERT INTITUIÇÕES --

-- INSERT DISCIPLINAS --
INSERT INTO DISCIPLINE (name) VALUES('LINGUA PORTUGUESA');
INSERT INTO DISCIPLINE (name) VALUES('MATEMÁTICA');
INSERT INTO DISCIPLINE (name) VALUES('CONHECIMENTOS GERAIS');
INSERT INTO DISCIPLINE (name) VALUES('CONHECIMENTOS ESPECÍFICOS');
INSERT INTO DISCIPLINE (name) VALUES('DIREITO ADMINISTRATIVO');
INSERT INTO DISCIPLINE (name) VALUES('BANCO DE DADOS');
INSERT INTO DISCIPLINE (name) VALUES('LINGUA INGLESA');
INSERT INTO DISCIPLINE (name) VALUES('ÉTICA');
INSERT INTO DISCIPLINE (name) VALUES('DIREITO CONSTITUCIONAL');
INSERT INTO DISCIPLINE (name) VALUES('DIREITO PENAL');
INSERT INTO DISCIPLINE (name) VALUES('DIREITO TRIBUTÁRIO');
INSERT INTO DISCIPLINE (name) VALUES('SOCIOLOGIA');
INSERT INTO DISCIPLINE (name) VALUES('HISTÓRIA');
INSERT INTO DISCIPLINE (name) VALUES('GEOGRAFIA');
INSERT INTO DISCIPLINE (name) VALUES('RACIOCÍNIO LÓGICO');
INSERT INTO DISCIPLINE (name) VALUES('ECONOMIA');
INSERT INTO DISCIPLINE (name) VALUES('INFORMÁTICA');
INSERT INTO DISCIPLINE (name) VALUES('LEGISLAÇÃO');
INSERT INTO DISCIPLINE (name) VALUES('DIREITO PREVIDENCIARIO');
INSERT INTO DISCIPLINE (name) VALUES('DIREITO DO CONSUMIDOR');
INSERT INTO DISCIPLINE (name) VALUES('DIREITO TRABALHISTA');
INSERT INTO DISCIPLINE (name) VALUES('BIOLOGIA');
INSERT INTO DISCIPLINE (name) VALUES('MEIO AMBIENTE');
INSERT INTO DISCIPLINE (name) VALUES('GENÉTICA');
INSERT INTO DISCIPLINE (name) VALUES('PROGRAMAÇÃO');
INSERT INTO DISCIPLINE (name) VALUES('DESENVOLVIMENTO WEB');
INSERT INTO DISCIPLINE (name) VALUES('REDES DE COMPUTADORES');
-- INSERT DISCIPLINAS --



