CREATE DATABASE SYSCONTEST;

USE SYSCONTEST;

CREATE TABLE INSTITUTION (
	idInstitution 		INT 		NOT NULL AUTO_INCREMENT,
	name				NVARCHAR(55),
	CONSTRAINT institutionPKC PRIMARY KEY (idInstitution)
);

CREATE TABLE DISCIPLINE (
	idDiscipline 		INT 		NOT NULL AUTO_INCREMENT,
	name 				NVARCHAR(45),
	CONSTRAINT 	disciplinePCK PRIMARY KEY (idDiscipline)
);



