
SELECT * FROM INSTITUTION;
SELECT * FROM DISCIPLINE;
SELECT * FROM SUBJECT;
SELECT * FROM EXAM;
SELECT * FROM QUESTION;
SELECT * FROM DISCIPLINE_QUESTION;

-- CONSULTAR TODOS OS SUBJECT DE CADA DISCIPLINA  --
SELECT S.idDiscipline, D.name, S.name, S.idSubject
FROM SUBJECT AS S, DISCIPLINE AS D
WHERE S.idDiscipline = D.idDiscipline;


-- CONSULTAR AS QUESTOES DA DISCIPLINA PORTUGUES --
SELECT Q.idQuestion, Q.idExam, Q.statement, Q.answer, Q.optionA, Q.optionB, Q.optionC, Q.optionD, Q.optionE  
FROM 	QUESTION AS Q, DISCIPLINE AS D, DISCIPLINE_QUESTION AS DQ
WHERE   Q.idQuestion = DQ.idQuestion AND
		D.idDiscipline = DQ.idDiscipline AND
		D.idDiscipline = 1;
-- CONSULTAR AS QUESTOES DA DISCIPLINA PORTUGUES --

