
SELECT * FROM INSTITUTION;
SELECT * FROM DISCIPLINE;
SELECT * FROM SUBJECT;
SELECT * FROM EXAM;

-- CONSULTAR TODOS OS SUBJECT DE CADA DISCIPLINA  --
SELECT S.idDiscipline, D.name, S.name, S.idSubject
FROM SUBJECT AS S, DISCIPLINE AS D
WHERE S.idDiscipline = D.idDiscipline;
